-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Anamakine: localhost
-- Üretim Zamanı: 07 Ağu 2017, 23:17:44
-- Sunucu sürümü: 5.7.19-0ubuntu0.16.04.1
-- PHP Sürümü: 7.0.18-0ubuntu0.16.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `eticaret`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `kategori`
--

CREATE TABLE `kategori` (
  `kategori_id` int(11) NOT NULL,
  `kategori_adi` varchar(30) CHARACTER SET utf8 COLLATE utf8_turkish_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `kategori`
--

INSERT INTO `kategori` (`kategori_id`, `kategori_adi`) VALUES
(1, 'Domates & Biber'),
(2, 'Süt & Peynir'),
(3, 'Yumurta'),
(4, 'Salça & Turşu'),
(5, 'Zeytin & Zeytinyağı'),
(6, 'Reçel & Bal'),
(7, 'Ekmek');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `siparis`
--

CREATE TABLE `siparis` (
  `siparis_id` int(11) NOT NULL,
  `urunler_id` varchar(11) NOT NULL,
  `users_mail` varchar(40) NOT NULL,
  `siparis_adet` varchar(11) NOT NULL,
  `toplamtutar` varchar(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `siparis`
--

INSERT INTO `siparis` (`siparis_id`, `urunler_id`, `users_mail`, `siparis_adet`, `toplamtutar`) VALUES
(1, '1', 'onurproje', '5', '350'),
(2, '5', '4', '3', '2'),
(3, '9', '9', '9', '9'),
(4, '1', 'onurproje', '5', '175.0');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `urunler`
--

CREATE TABLE `urunler` (
  `urun_id` int(11) NOT NULL,
  `urun_name` varchar(40) CHARACTER SET utf8 COLLATE utf8_turkish_ci NOT NULL,
  `urun_metin` varchar(250) CHARACTER SET utf8 COLLATE utf8_turkish_ci NOT NULL,
  `urun_aciklama` varchar(300) CHARACTER SET utf8 COLLATE utf8_turkish_ci NOT NULL,
  `urun_detay` varchar(3000) CHARACTER SET utf8 COLLATE utf8_turkish_ci NOT NULL,
  `urun_fotograf` varchar(400) NOT NULL,
  `urun_kategori` int(11) NOT NULL,
  `urun_fiyat` int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `urunler`
--

INSERT INTO `urunler` (`urun_id`, `urun_name`, `urun_metin`, `urun_aciklama`, `urun_detay`, `urun_fotograf`, `urun_kategori`, `urun_fiyat`) VALUES
(1, 'Eski Kaşar 500 Gr', '500 Gr Eski Kaşar Peyniri\r\n', 'Çiftliğimizin taptaze sütlerinden, geleneksel usullerle eski kaşar peyniri yapıyoruz. Ailece, afiyetle, güvenle tüketebilirsiniz.', 'İneklerimizin Mis Gibi Sütünden Eski Kaşar Peyniri!\n\nBergama\'daki çiftliğimizde, doğal beslenen, sağlıklı hayvanlarımızın taptaze sütünden taze kaşar peyniri yaptık. Eski kaşar peynirimizin yapımında inek sütümüz yanında, koyun ve keçi sütleri de bulunur. Lezzeti ve aroması da buradan gelir. \n\nEski kaşar peyniri üretiminde kullanılacak, el değmeden sağılmış taze sütler sabah erkenden süt çiftliğimizden alınır.  Gerekli kontrolleri yapıldıktan sonra süt pişirilir ve mayalanır. Maya tuttuğunda el becerisi ve özel kırım teknikleriyle teleme elde edilir, baskıya alınarak peynir altı suyu uzaklaştırılır. Teleme bu aşamada fermantasyona bırakılarak, daha sonra 65 - 75 derece arasında kendi suyu ile haşlama, yoğurma ve kalıplama yapılarak eski kaşar haline getirilir. Elde edilen eski kaşar peyniri özel dinlendirme odalarında salamura ve kuru tuzlama tekniklerinin ayrı ayrı uygulanması sonrasında en az 4 ay süreyle raflarda olgunlaştırılır. Olgunlaşma süresi içinde peynirin gerekli bakım i', 'https://i.hizliresim.com/77BvVa.png', 2, 35),
(2, 'Günlük Çiğ Süt ( 5 Lt )', '5 Lt Çiğ İnek Sütü', 'Doğal, mis gibi çiğ günlük süt siparişinizle taze taze çiftliğimizden kapınıza göndereceğiz. Siz sipariş verdiğinizde el değmeden sağacak; özel süt torbalarımızda, soğuk hava zinciri içerisinde paketleyeceğiz.', 'Günlük, Taze Çiğ Süt!\n\nÇiftliğimizin sütüyle yaptığımız, başka hiçbir yerde bulamayacağınız mis gibi doğal köy yoğurdunu evde maya çalmak için süt siparişinizle birlikte göndereceğiz. :)  Süt kokulu peynirlerimizin lezzetini veren mis gibi lezzetli sütümüzü de artık sizlerle paylaşabildiğimiz için çok mutluyuz. Lezzetli sütümüz, çiftliğimizde yetiştirdiğimiz ineklerimizin çiğ sütüdür. İnekler ne kadar sağlıklı olur, iyi bakılırsa sütleri de o kadar lezzetli olur. Bu yüzden bizler için hayvanlarımızın sağlığı, bakımı her şeyden önemlidir. İneklerimiz Bergama\'daki çiftliğimizde, uzman veteriner hekimler kontrolünde yetiştiriyoruz. Düzenli bakımları yine çiftliğimizde yapılıyor.\n\nHayvanlarımızı nasıl besliyoruz? Kendi tarlalarımızda yetiştirdiğimiz yonca, doğal mısır ve kuru otla besliyoruz. Kendi ürünlerimiz yetmediği zaman ise buradaki çiftçilerimizden aynı kalitedeki mahsulleri satın alıyoruz. İneklerimizi yazın ot, kışın slaj ile besliyoruz. Ayrıca onları domates yapraklarını yonc', 'https://i.hizliresim.com/r609m1.png', 2, 15),
(4, 'Çörekotlu Abaza Peyniri 250 Gr', '250 Gr Çörekotlu Abaza Peyniri\r\n', 'Abaza peynirimiz çörek otludur. Taze inek sütüyle elde edilir. Kahvaltılarda ve meze olarak çok lezzetli olur.', 'Nefis, Çörek Otlu Abaza Peyniri!\r\n\r\nÇiftliğimizde ineklerimizin taze sütüyle nefis Abaza peyniri de hazırladık. Biz bu lezzeti çok seviyoruz. Kahvaltıda, öğlen yemeklerinde çok lezzetli oluyor. Yapımına gelince? Abaza peyniri yapmak için mayalanmış peynir, içi su dolu kaynar bir kazana atılıp, erimesi beklenir ve sonrasında bir tahta kaşıkla döndüre döndüre toplanır. Sarılmadan öçörek otu serpilir. Çörek otu bu peynire ayrı bir lezzet katıyor. Üstelik çok sağlıklı bir gıdadır. Serin yerde, iyi bir şekilde muhafaza edildiğinde diğer peynirlere göre daha uzun ömürlü olabilir. Bekletilirse daha da bir lezzetli olur. Kahvaltılarda, kızartılarak, eritilerek ve sofralarda meze olarak çok lezzetli olur. Afiyet olsun.\r\n\r\nLütfen siparişlerinizi teslim aldığınız andan itibaren, peynir çeşitlerini buzdolabında muhafaza etmeye özen gösteriniz.\r\n\r\nPaket İçeriği: 350 gr vakumlanmış çörek otlu abaza peyniri ( İnek )', 'https://i.hizliresim.com/njbr5R.png', 2, 20),
(5, 'Mis Salkım Domates 250 Gr', '250 Gr Mis Salkım Domates', 'Mis salkım domatesimiz sulu yapısı, inceye yakın kabuğu ve kokusuyla baskın bir cins domatestir. Sipariş verdiğinizde toplarız. Taze taze adresinize yollarız.', 'Mis Kokulu Salkım Domates!\r\n\r\nSalkım domatesimiz sulu yapısı, inceye yakın kabuğu ve kokusuyla baskın bir cins domatestir.  Meyve kısımları ortalama 80-90 gr. ağırlığında olur. Meyveleri parlak ve koyu kırmızı renktedir. Salkım domateslerimizi topraklı seralarımızda yetiştiririz. Senede 4-5 kez hasadı biten fideler sökülür, yeniden dikim yapılır. Meyvenin güneş ışınlarından en iyi şekilde faydalanması için özel dikim usülleri uygulanır. Sipariş verdiğinizde toplarız, öyle mahsulü toplayıp soğuk hava depolarında bekletmeyiz. Hasadı gelmeyen mahsul kesinlikle toplanmaz. Çabuk olgunlaşsın diye kızartma gibi işlemler uygulanmaz. Bu cinsi yılın büyük zamanı yetiştiririz. Böylece size dalından toplayıp göndeririz. \r\n\r\nMis salkım domatesimizi hasadı geldiğinde toplarken dayanamaz, ısıra ısıra yeriz. Böyle yemenin keyfi bir başka oluyor. Söğüş olarak, salatalara, sandviçlere de çok yakışıyor. Salçalarımızı da bu domatesimizle yaparız, o da lezzetini salkım domatesten alır.\r\n\r\nDomateslerimizde ', 'http://i.hizliresim.com/6rDnbE.png', 1, 5),
(6, 'Meksika Biberi', '1 Kg Meksika Biber', 'Meksika biberimiz acı ve çıtır çıtırdır. et ve tavuk yemeklerine çok yakışır. Acı sevenlerin beğeneceğine eminiz.', 'Hormonsuz, Çıtır Çıtır Doğal Jalapeno Cinsi Biber!\r\n\r\nAcı sevenlerin bildiği, sevdiği bir biber türüdür. Lezzetli, hoş bir acılığ vardır. Meksika\'da menşeeli bir mahsüldür. Jalapeno biberi olarak da bilinir. Sosu ve turşusu yapılır. Tavuk ve et yemeklerine çok yakışır. \r\n\r\nPaket İçeriği: 1 Kg Acı Meksika Biberi \r\n', 'http://i.hizliresim.com/GPZzNN.png', 1, 8),
(7, 'Şeker Domates', '1 Kg Şeker Domates\r\n', 'Şeker domateslerimiz adı gibi şeker, lezzetli domates. Bir de mis kokusu var ki tadına doyulmaz.', 'Hormonsuz, Mis Kokulu Şeker Domates!\r\n\r\nBiz ona ‘’şeker domates’’ diyoruz. Bu cinsi siz şehirlerde, marketlerde ‘’cherry’’ domates ismiyle görürsünüz. Ama çiftliğimizin şeker domateslerinin lezzeti bir başkadır, onu marketlerde bulamazsınız. Şeker domatesimizi yalnızca hasadı geldiğinde toplarız. Hasadı bittiği zamanlarda soranı, bekleyeni çok olur. Meyveleri ortalama ceviz kadar, hafif oval olur. Çıtır çıtır lezzeti ve kokusu en önemli özelliğidir. Meyveleri parlak, kıpkırmızı olur. Domates reçelimizi de şeker domatesimizle yaparız çünkü kendi doğal tatlı lezzeti reçel yapımına çok uygundur. Onunla domates reçeli ayrı güzel olur. \r\n\r\nDomateslerimizde hormon yok, uzun ömürlü olması için kimyasal işlem yok. Bizim usullerimiz moderndir. Aynı zamanda gelenekselden kopmadan tarım yaparız. İyi tarım uygulamaları çerçevesinde mahsul yetiştiriyoruz. Mahsullerimizin lezzetine de kalitesine de güveniyoruz. Tüm mahsullerimiz hormonla değil; çiftliğimizin bombus arılarıyla tamamen doğal yöntemler', 'http://i.hizliresim.com/AnOJNz.png', 1, 14),
(8, 'Doğal Köy Yumurtası 15 Adet', '15 Adet Doğal Köy Yumurtası', 'Çiftliğimizin günlük, taze, hakiki köy yumurtaları. Her sabah taze taze toplarız, siparişiniz üzerine hazırlarız.', 'Doğal Köy Yumurtası 15 Adet resimleri\r\nDoğal Köy Yumurtası 15 Adet\r\n22,50 TL\r\n15 Adet Doğal Köy Yumurtası\r\nAdet:\r\n\r\n1\r\n Sepete Ekle >\r\nÜrün Özellikleri\r\n\r\nÇiftliğimizin günlük, taze, hakiki köy yumurtaları. Her sabah taze taze toplarız, siparişiniz üzerine hazırlarız.\r\n\r\n \r\nÜrün Detayları\r\nYorumlar\r\nGüvenle Tüketebilirsiniz\r\nTaze, Hakiki Köy Yumurtası!\r\n\r\n\r\nYumurtalarımız her daim taze ve lezzetlidir. Çünkü; çiftliğimizde sınırlı sayıda yumurta üretimi yaparız. Burası endüstriyel yumurta üretimi yapılan, binlerce tavuğu olan bir tesis değil. Belli sayıdaki tavuğumuzla, kümeslerimizde günlük toplayabildiğimiz yumurta 800 - 900 adedi geçmez. Çiftliğimizde tavukların topraktan yediği ottan, onları beslediğimiz yemlere, tavuklarımızın cinsinden, gelişim süreçlerine ve yaşam alanına kadar her aşaması doğaldır. Aynı zamanda veteriner hekimlerimiz tarafından düzenli olarak kontrol edilir. Özetle; Hasanbey Çiftliği\'nden yumurta aldığınızda evinizde, sofranızda hakiki köy yumurtasını afiyetle, ', 'http://i.hizliresim.com/X9b4AR.png', 3, 22),
(9, 'Doğal Köy Yumurtası 6 Adet', '6 Adet Doğal Köy Yumurtası', 'Çiftliğimizin günlük, taze, hakiki köy yumurtaları. Her sabah taze taze toplarız, siparişiniz üzerine hazırlarız.', 'Ürünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/5LNVJj.jpg', 3, 9),
(10, 'Doğal Köy Yumurtası 60 Adet', '60 Adet Doğal Köy Yumurtası', 'Çiftliğimizin günlük, taze, hakiki köy yumurtaları. Her sabah taze taze toplarız, siparişiniz üzerine hazırlarız.', 'Ürünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/0l0Dd9.png', 3, 80),
(11, 'Biber Turşusu ( Karışık ) 1425 Gr', '1425 Gr Biber Turşusu', 'Biber turşumuz eski usul, ev yapımı ve karışıktır. İçerisinde kendi mahsulümüz 4 çeşit biber, su, sarımsak bir de kaya tuzundan başka hiçbir şey yok. Biberlerimiz çiftliğimizin meşhur sarı, kırmızı, turuncu kapya biberleri ve acı yeşil biberlerimizdir.', 'Hormonsuz, Çıtır Çıtır, Karışık Biber Turşusu!\r\n\r\nÇiftliğimizde turşularımızı da sadece Metin Usta yapar.  O da annesinden öğrendiği, eski usullerle yapıyor. Karışık biber turşusunda 4 çeşit biber kullanıyor; sarı, kırmızı, turuncu kapya biberler ve acı yeşil biberler. Tabii ki bu biberleri çiftliğimizde yetiştiriyoruz. Turşu yapmak için önce biberler toplandıktan sonra yıkanıp, temizlenip doğranır. Doğrandıktan sonra turşu yapılacak kaplara basılır. Ardından sırasıyla kaya tuzu, nohut, sarımsak, limon ve biraz limon tuzu, çok az miktar da şeker ekleriz. En sonunda üzerine alabildiğine su eklenir. Bu şekilde hazırlandıktan sonra en az bir hafta sonra yenebilir.\r\n\r\n’Neden nohut konulur?’’ derseniz nohut turşunun mayasıdır. Turşuyu tutan, bozulmaz doğal bir mayadır. 10 kg kadar turşuya 1 avuç kadar nohut yeterli olur. Biz bir de sadece kaya tuzu kullanırız. Turşularımızın tuz oranı olması gerektiği kadardır fakat tuzsuz beslenmeye dikkat edenleriniz olursa azıcık temiz sudan geçirip öyle', 'http://i.hizliresim.com/6rDn4v.png', 4, 15),
(12, 'Acı Biber Salçası 1000 Gr', '1 Kg Acı Biber Salçası', 'Acı biber salçamızı çiftliğimizde yetiştirdiğimiz acı biberlerimizle yapıyoruz. İçerisinde katı yok, koryucu yok. Acı ve çok lezzetlidir.', 'Ev yapımı, Geleneksel Acı Biber Salçası!\r\n\r\nAcı biber salçamızı çiftliğimizde özenle yetiştirdiğimiz taze ve doğal biberlerimizi kullanarak tamamen geleneksel usullerle yapıyoruz. Biber salçamızda kırmızı kapya ve acı biberlerimizi kullanıyoruz. Tamamen katkısızdır; geleneksel yöntemlerle hazırlanır. Acı ve çok güzel bir lezzete sahiptir. Acı olduğunu göz önünde bulundurarak tüm yemeklerinizde, sofralarınızda kullanabilirsiniz. Dilerseniz katkısız domates salçamızla bir arada, birbirine karıştırarak kullanabilirsiniz. Çok lezzetli olacaktır.\r\n\r\nSalça yapma zamanı bizde Ağustos\'tur. Her yıl Ağustos ayında biberlerimiz toplanır, temizlenip salça yapımı için çekirdekleri ayrılır. Çekirdeklerinden ayrılıp az kaya tuzu konur. Sonra elde ettiğimiz malzemeyi muhafazalı ortamda güneşe sereriz. Daha sonra da kavanozlarımıza doldurup hava almaması için vakumlarız. Siz kavanozu açtıktan sonra üzerine kendi ürettiğimiz zeytin yağımızı ekleyebilir, bu şekilde muhafaza edebilirsiniz. \r\n\r\nAcıyı çok y', 'http://i.hizliresim.com/Yqdb1Z.png', 4, 25),
(13, 'Kahvaltılık Salça 1000 Gr', '1000 Gr Ev Yapımı Kahvaltılık Salça\r\n', 'Kahvaltılarda, yemeklerde sos olarak tüketebileceğiniz mis gibi domates salçası. Lezzetli, ev ve katkısız.', 'Ev Yapımı Geleneksel Kahvaltılık Salça!\r\n\r\nKahvaltılık salçamızda da kırmızı tombul domateslerimizi kullanıyoruz. Hem çok güzel suyunu veriyor hem de mis kokusuyla tombul domateslerimizle yaptığımız salçanın tanıdan doyum olmuyor. Önce domatesleri temizler, ayıklar, çekirdeklerinden ayrırız. Kahvaltılık salçamızı kazanda kaynatırız. Kaynatıldıktan sonra sıcak sıcak kavanozlara konur. Kapağı ters çevrilir. 1 gün öyle bekler. Bu şekilde 2 yıl raf ömrü vardır; bozulmaz. Açtıktan sonra ise 1 hafta / 10 gün içerisinde tüketmeniz gerekir.\r\n\r\nKahvaltılık salçamızda başka hiç bir koruyucu madde ya da raf ömrünü uzatacak uygulamalar yoktur. Domates, kaya tuzu, hepsi o kadar. Pişirirken, kavanozlara koyarken metal kaşık kullanmayız, sadece tahta kaşık. Tombul domatesin en lezzetli olduğu zamanda yani tam mevsiminde Ağustos aylarında hasat ettiğimiz domateslerle yaparız. Her Ağustos ayında da yenilerini hazırlarız. Bu arada biterse yeniden sipariş verebilmek için yaz aylarını beklemeniz gerekebil', 'http://i.hizliresim.com/Yqdb1Z.png', 4, 15),
(14, 'Süzme Yoğurt 1 Kg', '1 Kg Süzme Yoğurt', 'Doğal, katkısız ve ev yapımı... Çiftliğimizin sağlıklı, mis gibi sütleriyle hazırladığımız süzme yoğurdumuzu siparişinizle kapınıza göndereceğiz.', 'Çiftliğimizin Sütleriyle Ev Yapımı Süzme Yoğurt!\r\n\r\nSüzme yoğurdumuzu da çiftiliğimizin, kendi yetiştirdiğimiz ineklerimizin taptaze sütüyle yapıyoruz. Lezzetli sütümüz, çiftliğimizde yetiştirdiğimiz ineklerimizin çiğ sütüdür. İnekler ne kadar sağlıklı olur, iyi bakılırsa sütleri de o kadar lezzetli olur. Bu yüzden bizler için hayvanlarımızın sağlığı, bakımı her şeyden önemlidir. İneklerimiz Bergama\'daki çiftliğimizde, uzman veteriner hekimler kontrolünde yetiştiriyoruz. Düzenli bakımları yine çiftliğimizde yapılıyor.\r\n\r\nSüzme yoğurt yapmak için sabah erken saatte sağılan sütler mandıramıza gelir. Günlük sütümüz yüksek sıcaklıkta pastorize edildikten sonra, suyu uçurularak kuru maddesi yükseltilir. Süt bu sürecin ardından mayalama sıcaklığına  kadar soğutulur. Bildiğimiz ev yoğurdu kıvamında mayalandıktan sonra \'inkübasyon\' dediğimiz süre sonunda oluşan yoğurt soğutulur. Mayalarken de doğal, yine kendi yaptığımız yoğurdu kullanırız. Buna halk arasında ’’kara maya’’ da denir. Soğutulan ', 'https://i.hizliresim.com/o0d7Y7.png', 2, 2),
(15, 'Erişte Makarnası 450 Gr', '450 Gr Elde Kesme Erişte', 'Bergama’nın unu, suyuyla ev yapımı erişte makarnası... Tuz miktarı çok azdır. Hamuru ev yapımı yapıldıktan sonra yine elle dilimlenir.', 'Ev Yapımı, Katkısız Elde Kesme Erişte!\r\n\r\nElde kesme erişte makarnalarımızda da Metin Usta’nın el becerisi, marifetleri var. Metin Usta elde kesme erişte makarnası yapmak için önce 5 kg kadar una 2 kg kadar süt ve 25 adet köy yumurtası ile bir hamur yapar. Eriştenin hamuru biraz sert olur. Normalde 5 birim tuz konursa biz 1 birim koyarız. Yani çok az tuzu vardır. Bu sert hamur yoğurulduktan sonra yufka haline getirilip dinlendirilir; hamurun biraz kendini çekmesine bırakılır. Tamamen el marifetiyle dilimlendikten sonra kurutulur. Kurutması da yine oda sıcaklığında, muhafazalı ortamda yapılır.\r\n\r\nElde kesme erişte makarnasını yapması biraz zahmetlidir. Ama paketlenmiş makarnalarda bulamayacağınız bir lezzeti vardır. Çünkü eriştenin hamuru yöremizin yerel üreticilerinin doğal unlarıyla yapılır. Sütü ise ari süt çiftliği sertifikalı, deneyenlerin tadını çok iyi bildiği nefis sütlerimizden; yumurtaları ise yine çiftliğimizn taze, günlük köy yumurtalarındandır. Her türlü malzemesi yöremizde', 'http://i.hizliresim.com/NlLEyX.png', 4, 12),
(16, 'Menemen Sosu 370 Cc', '370 Cc Menemen Sosu\r\n', 'Kışlık konserve olarak da kullanabileceğiniz menemen sosumuz bol domates ve biberlidir. Ev yapımı ve katkısızdır. Mis gibi kokusunu kavanozu açtığınız anda alacaksınız.', 'Kışlık Menemen Sosu!\r\n\r\nYeni, çok güzel bir lezzet daha hazırladık sizin için; bir çeşit kışlık konserve olarak tüketeceğiniz menemen sosumuz hazır. Çok lezzetli, hele bir kokusu var ki kavanozun kapağını açtığınız anda siz de alacaksınız. Beğeneceğinize eminiz çünkü her birimiz çok emek vererek hazırladık. Ama bu güzel kışlık konservemizde en büyük marifet reçelleri, turşularıyla meşhur Metin Usta’mıza ait. Menemen sosumuz tamamen ev yapımı, köy usulü, içinde hiç bir katkı maddesi yok. \r\n\r\nMenemen sosumuzla kışın kahvaltılarda, köy yumurtalarımızla birlike lezzetli menemenler yapabilirsiniz. İçerisine sadece biraz baharat ekleyerek makarna, erişte sosu olarak kullanabilirsiniz. Yemeklerde kullanabilirsiniz. Mevsiminde toplanan o domateslerimzin misler gibi kokusu ve tadını alacaksınız. Menemen sosumuzun %80’inde bu yaz kısa bir süre hasat edebildiğimiz Çanakkale domateslerimiz var; geri kalan kısmında ise çıtır biberlerimiz. Yapımına gelince; önce Çanakkale domateslerimizi ve çıtır biberlerimizi yıkayıp ayıklıyoruz. Sonra tavada zeytinyağıyla birlikte diri diri kalacak şekilde biraz pişiriyoruz. Kavanozlara sıcak sıcak dolum yapılıp, konserve yapımında olduğu gibi kavanozları ters çevirerek vakumluyoruz. Bu şekilde tüm kış buzdolabında olmak koşuluyla muhafaza edebilirsiniz. Kapağını açtıktan sonra ise bir hafta içerisinde tüketmenizi öneririz.\r\n\r\n\r\nKavanoz İçeriği: 370 cc Ev Yapımı Menemen Sosu', 'http://i.hizliresim.com/WgXYl8.png', 4, 15),
(17, 'Lor Peyniri 500 Gr', '500 Gr Tam Yağlı Lor Peyniri\r\n', 'Lor peyniri yapmak için ineklerimizin sütünü hava müdahalesi olmadan, sağıldıktan 45 dakika içerisinde pastorize ediyor ve geleneksel Bergama Tulum Peyniri olarak mayalıyoruz. Geriye kalan peynir suyunu tamamen katkısız olarak; sadece tuz ve ısı ile lor peyniri yapıyoruz.', 'Lor Peynirimizi Yeniledik, Şimdi Daha da Lezzetli!\r\n\r\nLor peynirimiz artık tam yağlı ve daha lezzetli. Çiftliğimizin en çok tercih edilen, deneyen, tadına bakanların çok sevdiği bir peynirimiz. Sırrı ve marifeti ise çiftliğimizin emektarlarından Mustafa ustaya ait. Lor peynirlerimiz için ineklerimizin sütünü hava müdahalesi olmadan, sağıldıktan 45 dakika içerisinde pastorize ediyor ve geleneksel Bergama Tulum Peyniri olarak mayalıyoruz. Bu işlem sırasında peynir telemesi ayrılıyor. Geriye kalan peynir suyunu tamamen katkısız olarak; sadece tuz ve ısı ile lor peyniri yapıyoruz. Sonunda tam yağlı, protein deposu lor peyniri olarak vakumluyoruz. Çocuklarınızla, ailecek gönül rahatlığıyla tüketebilirsiniz. Salatalara, kahvaltılara, sandviçlere, böreklere... çok lezzetli olacak. Şimdiden afiyet olsun.\r\n\r\nLor peynirimiz katkısız ve tam yağlıdır. 100 gr Lor peynirimizin besin değerleri; 160 Kcal, Yağ 7,7 gr, Protein 12,19, Karbonhidrat 2,5 gr.\r\n\r\nLütfen siparişlerinizi teslim aldığınız andan itibaren, peynir çeşitlerini buzdolabında muhafaza etmeye özen gösteriniz.\r\n\r\nPaket İçeriği: 500 gr vakumlanmış lor peyniri ', 'https://i.hizliresim.com/LZv3Yb.png', 2, 18),
(18, 'Kekikli-Biberli Sepet Peyniri 300 Gr', '300 Gr Kekikli-Biberli Sepet Peyniri\r\n', 'Peynirlerimizi sağlıklı ineklerimizin taze sütleriyle yapıyoruz. Sepet peynirimiz de sepet kalıplar içerisinde şekillendirilmiş yöresel bir tattır.', 'İneklerimizin Tazecik Sütlerinden Sepet Peyniri!\r\n\r\nBergama\'daki çiftliğimizde, doğal beslenen, sağlıklı ineklerimizin tazecik sütünden sepet peyniri... Sepet peynirimiz, sepet kalıplar içerisinde şekillendirilmiş yöresel bir lezzettir. Tuz miktarı az, tam yağlı, kendine has bir lezzeti vardır. Tadı ve kıvamı tam yerindedir. Çeşitli baharatların çok yakıştığı bir peynir çeşididir. Kahvaltılarda, meze olarak ikram sofralarında afiyetle tüketebilirsiniz. \r\n\r\nLütfen siparişlerinizi teslim aldığınız andan itibaren, peynir çeşitlerini buzdolabında muhafaza etmeye özen gösteriniz. \r\n\r\n\r\nPaket İçeriği: 300 gr (net) Vakumlanmış Kekikli-Kırmızı Biberli Sepet Peyniri\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'https://i.hizliresim.com/vXa4Qp.png', 2, 7),
(19, 'Keçi Peyniri (350) Gr', '350 Gr Keçi Peyniri\r\n', 'Hayvanlarımızın tazecik sütleriyle yapılır. Tamamen katkısız ve natureldir. Olgunlaştırılma süresi 4 ile 6 ay arasındadır.', 'Taze Sütten, Nefis Keçi Peyniri!\r\n\r\nBeyaz peynirimiz çok beğendiğinizi biliyoruz. Şimdi keçilerimizin taze, sağlıklı sütüyle nefis Beyaz peynirimiz de hazır. Geleneksel yöntemlerle yapılmış ve katkısızdır. Hiçbir koruyucu madde kullanmadan, süt kokusu üzerinde, tadı ve kıvamı tam yerindedir peynirlerimizin. Beyaz peynirlerimizi vakumlu şekilde size gönderiyoruz. Tamamen katkısız ve natureldir. Olgunlaştırılma süresi 4 ile 6 ay arasındadır.  Taze taze tüketin, çocuklarınızla, ailenizle kahvaltı sofralarınızda keyfini çıkarın. Afiyet olsun. \r\n\r\nLütfen siparişlerinizi teslim aldığınız andan itibaren, peynir çeşitlerini buzdolabında muhafaza etmeye özen gösteriniz.\r\n\r\nPaket İçeriği: 350 gr vakumlanmış keçi peyniri\r\n\r\nTaze sütten, koruyucu olmadan!\r\n\r\nÇiftliğimizde beslenen sağlıklı ineklerin/keçilerin sütünden üretilir. Keçilerimiz ne kadar iyi beslenir, ne kadar iyi bir çiftlik ortamında yetişirlerse o kadar iyi süt verir; tazecik sütlerinin peynirleri de bir o kadar lezzetli olur. Biz de sağlıklı ineklerimizin, keçilerimizin sütü ve çiftliğimizdeki Fatma teyze, Metin Usta\'nın emekleriyle elde ettiğimiz keçi peynirini sizinle paylaşıyoruz.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'https://i.hizliresim.com/l3Q10E.jpg', 2, 17),
(20, 'Doğal Köy Yumurtası 30 Adet', '30 Adet Doğal Köy Yumurtası', 'Çiftliğimizin günlük, taze, hakiki köy yumurtaları. Her sabah taze taze toplarız, siparişiniz üzerine hazırlarız.', 'Taze, Hakiki Köy Yumurtası!\r\n\r\n\r\nYumurtalarımız her daim taze ve lezzetlidir. Çünkü; çiftliğimizde sınırlı sayıda yumurta üretimi yaparız. Burası endüstriyel yumurta üretimi yapılan, binlerce tavuğu olan bir tesis değil. Belli sayıdaki tavuğumuzla, kümeslerimizde günlük toplayabildiğimiz yumurta 800 - 900 adedi geçmez. Çiftliğimizde tavukların topraktan yediği ottan, onları beslediğimiz yemlere, tavuklarımızın cinsinden, gelişim süreçlerine ve yaşam alanına kadar her aşaması doğaldır. Aynı zamanda veteriner hekimlerimiz tarafından düzenli olarak kontrol edilir. Özetle; Hasanbey Çiftliği\'nden yumurta aldığınızda evinizde, sofranızda hakiki köy yumurtasını afiyetle, güvenle yiyebilirsiniz.\r\n\r\nYem rasyonumuzu kendimiz, veteriner hekimlerimiz kontrolünde çiftliğimizde hazırlarız. Hazır yem kullanmayız. Her gün folluklardan toplanan günlük, taze yumurtalarımız paketleme alanımıza gelir ve burada siparişleriniz için teker teker sarıp sarmalanır. Ambalajlarımızda sağlıklı, doğal ve iyi malzeme kullanırız; çünkü yumurta kabuğu canlı, nefes alan bir besindir.  Ailece, afiyetle ve güvenle tüketebilirsiniz. \r\n\r\nBiz hiç ‘’gezmeyen tavuk’’ görmedik, bilmeyiz. ‘’Özgür tavuk’’ diyorlar, özgür olmayanını da bilmiyoruz. Bizim tavuklarımız geniş kümeslerimizde ve onlar için ayrılan korunaklı alanda istedikleri gibi gezinirler. Hazır yem kullanmayız. Her gün folluklardan toplanan günlük, taze yumurtalar, paketleme alanımıza gelir ve burada siparişleriniz için teker teker sarıp sarmalanır. Size sapasağlam ulaştırmak için ayrıca özen gösteririz. Yumurtalarımızı ailenizle birlikte, gönül rahatlığıyla yiyin. Afiyet olsun. \r\n\r\nPaket İçeriği: 30 Adet taze, günlük köy yumurtası\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )', 'https://i.hizliresim.com/bkvb3d.png', 3, 19),
(21, 'Taze Bamya 1 Kg', '1 Kg Taze Bamya\r\n', 'Taze bamyalarımızı günlük hasat ederiz. Çiftliğimizin yakınlarında, yöreli çiftçiler ile yetiştiriyoruz. Gövdesi yumuşak ve lezzetlidir.', 'Hormonsuz, günlük hasat ettiğimiz taze bamya!\r\n\r\nBu yıl yine çiftliğimizin yakınlarında, yöreli çiftçilerimiz ile birlikte bamya yetiştirmeye başladık. Çok şükür bereketli topraklarımızda her şey yetişiyor. Bizde elimizden geldiğince etraftaki çiftçilerimize destek olmaya, yardımcı olmaya çalışıyoruz. Bamyalarımız da çok lezzetli, bereketli oldu. Bamya sebzesi genellikle Haziran ayında hasat edilir. Bizde günlük hasat ederiz. Bamya sebzesi tazeyken toplanmalıdır. Daha sonra yaş veya kurutularak tüketilir. Bamyalarımızın meyvesinin eti yumuşak ve çok lezzetlidir. Zeytinyağlısı, etlisi, çorbası, kıymalısı, hatta turşusu… Hepsi çok lezzetli olur. Biz buralarda kızartmasını bile yapıyoruz. Nasıl yapılır anlatalım; önce yumurtaya sonra mısır ununa bulayıp kızartıyorsunuz. Yanına da yoğurt oldu mu çok lezzetli oluyor. Bamyalarımızı siz de stediğiniz gibi pişirebilir, ailece afiyetle tüketebilirsiniz. \r\n\r\nBamya lezzetli olduğu kadar çok da faydalı bir sebzedir. Uzman doktorlara göre sindirim sisteminin güzel çalışmasına yardımcı oluyormuş; doğrudur. Lif oranı çok yüksektir. Mineraller açısından çok zengindir. Emek verip yetiştirdiğimiz bamyalarımızı sipariş verin, sizin için toplayalım, bekletmeden taze taze gönderelim.\r\n\r\nPaket İçeriği: 1 Kg tazecik bamya ', 'https://i.hizliresim.com/d8LbD7.png', 1, 26),
(22, 'Patlıcan 1 Kg', '1 Kg Patlıcan\r\n', 'Çifliğimizde yetiştirdiğimiz taze patlıcanlarımız uzun siyah patlıcan olarak da bilinen bir cinstir. Orta boyda, yumuşak bir yapıdadır. Özelikle yemeklik bi cinstir.', 'Taze Taze Lezzetli Uzun Patlıcan!\r\n\r\nÜretince, emek verince yapamayacağımız şey yok... Bu yıl da çiftliğimizde ilk kez, daha çok miktarlarda patlıcan hasat ettik. Daha nce yetiştirdiklerimiz ancak bizlere yetiyordu ama şimdi sizinle paylaşabileceğimiz kadar çok verim almaya başladık. Çifliğimizde yetiştirdiğimiz taze patlıcanlarımız uzun patlıcan olarak da bilinen bir cinstir. Orta boyda, yumuşak bir yapıdadır. Patlıcanlarımızı çiftliğimizin açık alanlarında, tarlalarımızda yetiştiriyoruz. Özelikle yemeklik bi cinstir. Her türlü patlıcanlı yemeklerinizde afiyetle kullanabilirsiniz. \r\n\r\nKızartması da çok lezzetli olur. Yağ çekmez, tazecik olduğu için çabuk pişer. Patlıcanlarımızı da siz sipariş verdiğinizde toplayıp, kırmızı kutularımızda kargoya vereceğiz. Soğuk hava depolarında, hallerde günlerce bekletmeden sofranıza ulaştıracağız. Biz çok emek verdik, yetiştirdik sizin de denemenizi çok istiyoruz. \r\n\r\nPaket İçeriği: 1 kg taze çıtır patlıcan \r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'https://i.hizliresim.com/bkvbpG.png', 1, 8),
(23, 'Dolgulu Yeşil Zeytin( Biberiyeli) 500 ', '500 Gr Biberiye Dolgulu\r\n', 'Zeytinlerimizi Ayvalık\'ın Kozak yaylası ve deniz arasında kalan topraklarımızda yetiştiriyoruz. Geleneksel yöntemlerler dolduruyor, salamura ediyoruz.', 'Biberiye Dolgulu Nefis Yeşil Zeytin!\n\nYeşil zeytinlerimiz zaten çok lezzetli, bir de biberiye dolgulusunu hazırlayalım istedik. Çok lezzetli oldu. :) Ayvalık\'ın en kaliteli zeytinlerinin elde edildiği Kozak Yaylası ile deniz arasında kalan bölgede yetiştirdiğimiz zeytinlerimizi, geleneksel yöntemlerle hazırlıyorve kavanozlara dolduruyoruz. Biberiye dolgulu zeytinlerimiz hem çok lezzetli, hem de sofralarına çok yakışacak.\n\nBiberiye dolgulu yeşil zeytinlerimizde biberiyenin hafif bir acılığı vardır. Fakat güzel bir lezzet veriyor. Turşu tadını ve turşu yerken aldığınız damak zevkini biberiye dolgulu zeytinleirmizde alacaksınız. \n\nKavanoz İçeriği: 500 gr (net) Biberiye Dolgulu Yeşil Zeytin\n\nKimyasal yok, Mumlama yok!\n\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )\n\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\n\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/m4XEbZ.jpg', 5, 13),
(24, 'Yeşil Zeytin ( Kırma ) 450 Gr', '450 Gr Yeşil Domat Kırma\r\n', 'Zeytinlerimizi Ayvalık\'ın en iyi zeytinlerinin elde edildiği Kozak yaylası ve deniz arasında kalan bölgede yetiştiriyoruz. Geleneksel yöntemlerle hazırlıyor, salamura ediyoruz.', 'Geleneksel Lezzet!\r\n\r\nEge\'nin mis kokulu topraklarının mahsüllerinden domat kırma yeşil zeytin... Biz zeytinlerimizi Ayvalık\'ın en kaliteli zeytinlerinin elde edildiği Kozak Yaylası ile deniz arasında kalan bölgede yetiştiriyoruz. Nesillerdir uygulanan geleneksel yöntemlerle hazırlıyor ve kavanozlara dolduruyoruz.  Katkı maddesi ya da koruyucu kullanmıyoruz.\r\n\r\nHerhangi bir katkı veya koruyucu içermez. Geleneksel yöntemlerle hazırlanmış, özel bir üretimdir. Sofralık, kahvaltılarda tüketebileceğiniz bir zeytin çeşididir. Zeytinler ağaçta hafif sarı veya mora dönmeye başladığında elle toplanır. Ayvalık zeytininin en önemli özelliği kendine has bir yapısının olmasıdır. Ayvalığın iyotlu havası ve toprağının aroması mahsule özel lezzetini verir.\r\n\r\n\r\nKavanoz İçeriği: 300gr (net) Domat Kırma Yeşil Zeytin\r\n\r\nEge\'nin en iyisi, en lezzetlisi!\r\n\r\nHerhangi bir katkı veya koruyucu içermez. Geleneksel yöntemlerle hazırlanmış, özel bir üretimdir. Sofralık, kahvaltılarda tüketebileceğiniz bir zeytin çeşididir. Gemlik türü, siyah sofralık olarak en kaliteli zeytin çeşitlerindendir. Özelliği ince kabuklu, küçük çekirdekli ve etli oluşudur.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/ErO3LB.jpg', 5, 17),
(25, 'Yeşil Zeytin ( Çizik ) 450 Gr', '450 Gr Yeşil Edremit\r\n', 'Zeytinlerimizi Ayvalık\'ın en iyi zeytinlerinin elde edildiği Kozak yaylası ve deniz arasında kalan bölgede yetiştiriyoruz. Geleneksel yöntemlerle hazırlıyor, salamura ediyoruz.', 'Geleneksel Lezzet!\r\n\r\nEge\'nin mis kokulu topraklarının mahsüllerinden yeşil edremit zeytin... Biz zeytinlerimizi Ayvalık\'ın en kaliteli zeytinlerinin elde edildiği Kozak Yaylası ile deniz arasında kalan bölgede yetiştiriyoruz. Nesillerdir uygulanan geleneksel yöntemlerle hazırlıyor ve kavanozlara dolduruyoruz.  Katkı maddesi ya da koruyucu kullanmıyoruz.\r\n\r\nHerhangi bir katkı veya koruyucu içermez. Geleneksel yöntemlerle hazırlanmıştır, özel üretimdir. Sofralık, kahvaltılarda tüketebileceğiniz bir zeytin çeşididir. Sonbahar aylarında yeşil taneler renk atmaya başladığında toplanır. Tamamen doğal yöntemlerle tatlandırılır. \r\n\r\n\r\nKavanoz İçeriği: 300gr (net) Yeşil Çizik Zeytin\r\n\r\nEge\'nin en iyisi, en lezzetlisi!\r\n\r\nHerhangi bir katkı veya koruyucu içermez. Geleneksel yöntemlerle hazırlanmış, özel bir üretimdir. Sofralık, kahvaltılarda tüketebileceğiniz bir zeytin çeşididir. Gemlik türü, siyah sofralık olarak en kaliteli zeytin çeşitlerindendir. Özelliği ince kabuklu, küçük çekirdekli ve etli oluşudur.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/jXqBMD.jpg', 5, 12),
(26, 'Siyah Zeytin ( Gemlik ) 440 Gr', '440 gr Siyah Gemlik\r\n', 'Zeytinlerimizi Ayvalık\'ın en iyi zeytinlerinin elde edildiği Kozak yaylası ve deniz arasında kalan bölgede yetiştiriyoruz. Geleneksel yöntemlerle hazırlıyor, salamura ediyoruz.', 'Geleneksel lezzet!\r\n\r\nEge\'nin mis kokulu topraklarının mahsüllerinden siyah yağlı sele zeytin... Biz zeytinlerimizi Ayvalık\'ın en kaliteli zeytinlerinin elde edildiği Kozak Yaylası ile deniz arasında kalan bölgede yetiştiriyoruz. Nesillerdir uygulanan geleneksel yöntemlerle hazırlıyor ve kavanozlara dolduruyoruz.  Katkı maddesi ya da koruyucu kullanmıyoruz.\r\n\r\nGemlik zeytinimizin rengi doğal koyu siyahtır. Dalında karardıktan sonra toplanır. Kimyasal işlem görmez. Toplandıktan sonra, bekletilmeden salamura edilir. Çekrideği etinden kolayca ayrılan bir çeşittir. İnce kabuklu, küçük çekirdekli ve etlidir. Kahvaltı sofralarımızın vazgeçilmez lezzetidir. Sofralarımızın tek zenginliği zeytinimizdir. \r\n\r\nKavanoz İçeriği: 300gr (net) Siyah Zeytin Yağlı Sele (Gemlik Tipi)\r\n\r\nEge\'nin en iyisi, en lezzetlisi!\r\n\r\nHerhangi bir katkı veya koruyucu içermez. Geleneksel yöntemlerle hazırlanmış, özel bir üretimdir. Sofralık, kahvaltılarda tüketebileceğiniz bir zeytin çeşididir. Gemlik türü, siyah sofralık olarak en kaliteli zeytin çeşitlerindendir. Özelliği ince kabuklu, küçük çekirdekli ve etli oluşudur.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/2nOjdd.jpg', 5, 19),
(27, 'Naturel Sızma Zeytinyağı', '750 Ml Naturel Sızma\r\n', 'Zeytinyağımız taş baskıda, soğuk sıkım yöntemiye elde edilir. İçinde katkı veya koruyucu yoktur.', 'Taş Baskı Doğal Lezzet!\r\n\r\nSofralarınızda, mutfağınızda kullanabileceğiniz en özel, en lezzetli zeytinyağı... Ege\'nin mis kokulu topraklarının mahsulü zeytinlerden, taş baskı usulüyle taze taze üretilir. Katkı maddesi ve koruyucu yoktur. Taş baskı usulüyle Ayvalık tarafında yetiştirdiğimiz zeytinler, en saf haliyle taş değirmenlerde ezilerek hamur haline getirilir ve soğuk preslerde sızma yoluyla saf zeytinyağı ayrıştırılır. Soğuk sıkım yöntemi zeytinin dalındaki tüm vitamini ve minreallerini korunmasını sağlar. En sonunda da kahvaltılarınızda ekmek banarak yiyebileceğiniz lezzet ve saflıkta zeytinyağı elde ederiz. \r\n\r\n\r\nCam Şişe İçeriği: 750 ml ( net ) naturel sızma zeytinyağı\r\n\r\nEge\'nin en iyisi, naturel sızma...\r\n\r\nKatkı veya koruyucu içermez. Taş baskı usulüyle hazırlanmıştır. Hasanbey Çiftliği tarafından özel olarak ürettirilmiştir. Serbest yağ asidi en çok %0,8 oranındadır. +5°\'nin altında donabilir. Tekrar çözülmesi kalitesini etkilemez. Gün ışığı ve ısıdan korunmalıdır.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/BvO8nQ.jpg', 5, 27),
(28, 'Erken Hasat Zeytinyağı', '500 Ml Erken Hasat\r\n', 'Zeytinyağımız taş baskıda, soğuk sıkım yöntemiye elde edilir. İçinde katkı veya koruyucu yoktur.', 'Taş Baskı Doğal Lezzet!\r\n\r\nSofralarınızda, mutfağınızda kullanabileceğiniz en özel, en lezzetli zeytinyağı... Ege\'nin mis kokulu topraklarının mahsulü zeytinlerden, taş baskı usulüyle taze taze üretilir. Katkı maddesi ve koruyucu yoktur. Taş baskı usulüyle Ayvalık tarafında yetiştirdiğimiz zeytinler, en saf haliyle taş değirmenlerde ezilerek hamur haline getirilir ve soğuk preslerde sızma yoluyla saf zeytinyağı ayrıştırılır. Soğuk sıkım yöntemi zeytinin dalındaki tüm vitamini ve minreallerini korunmasını sağlar. En sonunda da kahvaltılarınızda ekmek banarak yiyebileceğiniz lezzet ve saflıkta zeytinyağı elde ederiz. \r\n\r\n\r\nCam Şişe İçeriği: 500 ml ( net ) erken hasat zeytinyağı\r\n\r\nEge\'nin en iyisi, erken hasat...\r\n\r\nKatkı veya koruyucu içermez. Taş baskı usulüyle hazırlanmıştır. Hasanbey Çiftliği tarafından özel olarak ürettirilmiştir. Serbest yağ asidi en çok %0,8 oranındadır. +5°\'nin altında donabilir. Tekrar çözülmesi kalitesini etkilemez. Gün ışığı ve ısıdan korunmalıdır.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/BvO8nQ.jpg', 5, 24),
(29, 'Dolgulu Yeşil Zeytin ( Kırmızı Biberli )', '500 Gr Kırmızı Biber Dolgulu\r\n', 'Zeytinlerimizi Ayvalık\'ın Kozak yaylası ve deniz arasında kalan topraklarımızda yetiştiriyoruz. Geleneksel yöntemlerler dolduruyor, salamura ediyoruz.', 'Kırmızı Biber Dolgulu Nefis Yeşil Zeytin!\r\n\r\nYeşil zeytinlerimiz zaten çok lezzetli, bir de kırmızı biber dolgulusunu hazırlayalım istedik. Çok lezzetli oldu. :) Ayvalık\'ın en kaliteli zeytinlerinin elde edildiği Kozak Yaylası ile deniz arasında kalan bölgede yetiştirdiğimiz zeytinlerimizi, geleneksel yöntemlerle hazırlıyor ve kavanozlara dolduruyoruz. Kırmızı biber dolgulu zeytinlerimiz hem çok lezzetli, hem de sofralarına çok yakışacak.\r\n\r\nKahvaltıya çok yakışan kırmızı biber dolgulu zeytinlerimizi ikram sofralarınızda da yer verebilirsiniz. \r\n\r\nKavanoz İçeriği: 500 gr (net) Kırmızı Biber Dolgulu Yeşil Zeytin\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/ZM5Y6o.png', 5, 25),
(30, 'Dolgulu Yeşil Zeytin ( Bademli ) 500 Gr', '500 Gr Badem Dolgulu Zeytin\r\n', 'Zeytinlerimizi Ayvalık\'ın Kozak yaylası ve deniz arasında kalan topraklarımızda yetiştiriyoruz. Geleneksel yöntemlerler dolduruyor, salamura ediyoruz.', 'Badem Dolgulu Nefis Yeşil Zeytin!\r\n\r\nYeşil zeytinlerimiz zaten çok lezzetli, bir de badem dolgulusunu hazırlayalım istedik. Çok lezzetli oldu. :) Ayvalık\'ın en kaliteli zeytinlerinin elde edildiği Kozak Yaylası ile deniz arasında kalan bölgede yetiştirdiğimiz zeytinlerimizi, geleneksel yöntemlerle hazırlıyorve kavanozlara dolduruyoruz. Badem dolgulu zeytinlerimiz hem çok lezzetli, hem de sofralarına çok yakışacak.\r\n\r\nKavanoz İçeriği: 500 gr (net) Badem Dolgulu Yeşil Zeytin\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/njbEdB.jpg', 5, 21),
(31, 'Çörekotlu Köy Ekmeği (750 Gr)', '750 Gr Ekşi Mayalı Köy Ekmeği\r\n\r\n', 'Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyor; kendi yaptığımız ekşi mayalarımızı kullanıyoruz.', 'Tam Buğday Unlu, Ekşi Mayalı Çörek Otlu Ekmeğimiz!\r\n\r\nTaş fırında pişen, lezzetli, taze ekmeğimizin tarifi de mahareti de annelerimizden & çiftçimizden... Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyoruz. Üstelik mayamız da çok eskilerden bu yana bilinen ekşi maya. Ekşi mayalarımızı kendimiz, günlerce emek vererek yapıyoruz. Çörek otu da ekmeğimize çok yakışıyor. Şimdilerde ekşi maya ile ekmek yapmak biraz zahmetli, sabır gerektiriyor ama her yerde bulamayacağınız da bir lezzet veriyor. O yüzden ekmeklerimiz lezzetli olduğu kadar sağlıklı, vitamini ve lifi boldur. Buzdolabında, kendi ambalajında sakladığınızda 15 gün kadar dayanır. Dışardan alıdığınız, hazır mayalı ekmeklere göre daha sert gelebilir. Bu nedenle kızartıp ısıtarak sıcak sıcak, ailece tüketebilirsiniz. Tostu çok güzel olur. \r\n\r\nÖnemli not: Ekmeklerimizi sipariş verdiğiniz tarihte hazırlayıp, günlük olarak kargoya vereceğiz. Örneğin; Pazartesi 16:00\'ya kadar verdiğiniz ekmek siparişleri aynı gün  hazırlanıp size ulaşmak üzere yola çıkacak. Hafta sonu siparişlerinizi ise yine Pazartesi sabahı kargoya vereceğiz. Şimdiden afiyet olsun.\r\n\r\nPaket İçeriği: 750 gr ekşi mayalı tam buğday unlu çörek otlu köy ekmeği\r\n\r\nTam buğday unlu, çörek otlu mis gibi taş fırın ekmeği!\r\n\r\nTam buğday unu "buğday taneciğini tamamen içeren" undur. Ekmek tam buğday unu ile pişirilirse buğdayın doğal yapısında bulunan vitamin, mineral ve posayı en iyi şekilde içerir. Ekşi maya un ve suyu ekmek haline getiren en eski yoldur. Ekşi mayalı ekmek geç bayatlar; sindirimi kolay olur. Glisemik indeksi düşüktür. Kan şekerinizi hızla yükseltmez uzun süre tok tutar. Besleyicidir, B vitamininden zengindir. Ekşi mayalı ekmek tüketmek vücudunuzdaki B12 vitaminini arttırır. Ekmeğimiz saklama koşulu olarak buzdolabı şartların da 15 gün dayanmaktadır. Önerimiz size ulaştırdığımız ambalajda saklamanızdır. Afiyet olsun.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz.', 'http://i.hizliresim.com/VPQPVv.png', 7, 7);
INSERT INTO `urunler` (`urun_id`, `urun_name`, `urun_metin`, `urun_aciklama`, `urun_detay`, `urun_fotograf`, `urun_kategori`, `urun_fiyat`) VALUES
(32, 'Köy Ekmeği (750 Gr)', '750 Gr Ekşi Mayalı Köy Ekmeği\r\n', 'Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyor; kendi yaptığımız ekşi mayalarımızı kullanıyoruz.', 'Tam Buğday Unlu, Ekşi Mayalı Odun Ateşinde Pişen Ekmeğimiz!\r\n\r\nTaş fırında pişen, lezzetli, taze ekmeğimizin tarifi de mahareti de annelerimizden & çiftçimizden... Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyoruz. Üstelik mayamız da çok eskilerden bu yana bilinen ekşi maya. Şimdilerde ekşi maya ile ekmek yapmak biraz zahmetli, sabır gerektiriyor ama her yerde bulamayacağınız da bir lezzet veriyor. O yüzden ekmeklerimiz lezzetli olduğu kadar sağlıklı, vitamini ve lifi bol... Buzdolabında sakladığınızda ise 15 gün boyunca dayanır. Kızartıp ısıtarak sıcacık şekilde ailecek tüketebilirsiniz.\r\n\r\nÖnemli not: Ekmeklerimizi sipariş verdiğiniz tarihte hazırlayıp, günlük olarak kargoya vereceğiz. Örneğin; Pazartesi 16:00\'ya kadar verdiğiniz ekmek siparişleri aynı gün  hazırlanıp size ulaşmak üzere yola çıkacak. Hafta sonu siparişlerinizi ise yine Pazartesi sabahı kargoya vereceğiz. Şimdiden afiyet olsun.\r\n\r\nPaket İçeriği: 750 gr ekşi mayalı tam buğday unlu sade köy ekmeği\r\n\r\nTam buğday unlu, ekşi mayalı mis gibi köy ekmeği!\r\n\r\nTam buğday unu "buğday taneciğini tamamen içeren" undur. Ekmek tam buğday unu ile pişirilirse buğdayın doğal yapısında bulunan vitamin, mineral ve posayı en iyi şekilde içerir. Ekşi maya un ve suyu ekmek haline getiren en eski yoldur. Ekşi mayalı ekmek geç bayatlar; sindirimi kolay olur. Glisemik indeksi düşüktür. Kan şekerinizi hızla yükseltmez uzun süre tok tutar. Besleyicidir, B vitamininden zengindir. Ekşi mayalı ekmek tüketmek vücudunuzdaki B12 vitaminini arttırır. Ekmeğimiz saklama koşulu olarak buzdolabı şartların da 15 gün dayanmaktadır. Önerimiz size ulaştırdığımız ambalajda saklamanızdır. Afiyet olsun.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz. ', 'http://i.hizliresim.com/l3Q37r.png', 7, 6),
(33, 'Susamlı Tam Buğday Ekmeği (750 Gr)', '750 Gr Ekşi Mayalı Köy Ekmeği\r\n', 'Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyor; kendi yaptığımız ekşi mayalarımızı kullanıyoruz.', 'Tam Buğday Unlu, Ekşi Mayalı Odun Ateşinde Pişen Ekmeğimiz!\r\n\r\nTaş fırında pişen, lezzetli, taze ekmeğimizin tarifi de mahareti de annelerimizden & çiftçimizden... Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyoruz. Üstelik mayamız da çok eskilerden bu yana bilinen ekşi maya. Ekşi mayalarımızı kendimiz, günlerce emek vererek yapıyoruz. Şimdilerde ekşi maya ile ekmek yapmak biraz zahmetli, sabır gerektiriyor ama her yerde bulamayacağınız da bir lezzet veriyor. O yüzden ekmeklerimiz lezzetli olduğu kadar sağlıklı, vitamini ve lifi boldur. Buzdolabında, kendi ambalajında sakladığınızda 15 gün kadar dayanır. Dışardan alıdığınız, hazır mayalı ekmeklere göre daha sert gelebilir. Bu nedenle kızartıp ısıtarak sıcak sıcak, ailece tüketebilirsiniz. Tostu çok güzel olur. \r\n\r\nÖnemli not: Ekmeklerimizi sipariş verdiğiniz tarihte hazırlayıp, günlük olarak kargoya vereceğiz. Örneğin; Pazartesi 16:00\'ya kadar verdiğiniz ekmek siparişleri aynı gün  hazırlanıp size ulaşmak üzere yola çıkacak. Hafta sonu siparişlerinizi ise yine Pazartesi sabahı kargoya vereceğiz. Şimdiden afiyet olsun.\r\n\r\nPaket İçeriği: 750 gr ekşi mayalı tam buğday unlu susamlı köy ekmeği\r\n\r\nTam buğday unlu, susamlı mis gibi taş fırın ekmeği!\r\n\r\nEkşi maya un ve suyu ekmek haline getiren en eski yoldur. Ekşi mayalı ekmek geç bayatlar; sindirimi kolay olur. Glisemik indeksi düşüktür. Kan şekerinizi hızla yükseltmez uzun süre tok tutar. Besleyicidir, B vitamininden zengindir. Ekşi mayalı ekmek tüketmek vücudunuzdaki B12 vitaminini arttırır. Ekmeğimiz saklama koşulu olarak buzdolabı şartların da 15 gün dayanmaktadır. Önerimiz size ulaştırdığımız ambalajda saklamanızdır. Afiyet olsun.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/ZM5MDV.png', 7, 8),
(34, 'http://i.hizliresim.com/o0d0g9.png', '500 Gr Ekşi Mayalı Köy Ekmeği\r\n', 'Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyor; kendi yaptığımız ekşi mayalarımızı kullanıyoruz.', 'Tam Buğday Unlu, Ekşi Mayalı Odun Ateşinde Pişen Ekmeğimiz!\r\n\r\nTaş fırında pişen, lezzetli, taze ekmeğimizin tarifi de mahareti de annelerimizden & çiftçimizden... Güzel Ege\'mizin en iyi ununu kullanıyoruz; taş fırında, mis gibi odun ateşinde pişiriyoruz. Halis muhlis tam buğday unu ile yapıyoruz. Üstelik mayamız da çok eskilerden bu yana bilinen ekşi maya. Ekşi mayalarımızı kendimiz, günlerce emek vererek yapıyoruz. Şimdilerde ekşi maya ile ekmek yapmak biraz zahmetli, sabır gerektiriyor ama her yerde bulamayacağınız da bir lezzet veriyor. O yüzden ekmeklerimiz lezzetli olduğu kadar sağlıklı, vitamini ve lifi boldur. Buzdolabında, kendi ambalajında sakladığınızda 15 gün kadar dayanır. Dışardan alıdığınız, hazır mayalı ekmeklere göre daha sert gelebilir. Bu nedenle kızartıp ısıtarak sıcak sıcak, ailece tüketebilirsiniz. Tostu çok güzel olur. \r\n\r\nÖnemli not: Ekmeklerimizi sipariş verdiğiniz tarihte hazırlayıp, günlük olarak kargoya vereceğiz. Örneğin; Pazartesi 16:00\'ya kadar verdiğiniz ekmek siparişleri aynı gün  hazırlanıp size ulaşmak üzere yola çıkacak. Hafta sonu siparişlerinizi ise yine Pazartesi sabahı kargoya vereceğiz. Şimdiden afiyet olsun.\r\n\r\nPaket İçeriği: 750 gr ekşi mayalı tam buğday unlu sade köy ekmeği\r\n\r\nTam buğday unlu, susamlı mis gibi taş fırın ekmeği!\r\n\r\nTam buğday unu "buğday taneciğini tamamen içeren" undur. Ekmek tam buğday unu ile pişirilirse buğdayın doğal yapısında bulunan vitamin, mineral ve posayı en iyi şekilde içerir. Ekşi maya un ve suyu ekmek haline getiren en eski yoldur. Ekşi mayalı ekmek geç bayatlar; sindirimi kolay olur. Glisemik indeksi düşüktür. Kan şekerinizi hızla yükseltmez uzun süre tok tutar. Besleyicidir, B vitamininden zengindir. Ekşi mayalı ekmek tüketmek vücudunuzdaki B12 vitaminini arttırır. Ekmeğimiz saklama koşulu olarak buzdolabı şartların da 15 gün dayanmaktadır. Önerimiz size ulaştırdığımız ambalajda saklamanızdır. Afiyet olsun.\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. ', 'http://i.hizliresim.com/o0d0g9.png', 7, 7),
(35, 'Doğal Bal 450 Gr ( Çam Balı )', '450 Gr Çam Balı\r\n', 'Çiftliğimizde arılarımız mis kokulu çiçeklerden aldıkları özütleri bala çeviriyor. Ballarımızı da sadece çiftliğimizde üretiyoruz, bal peteklerimizle kendimiz ilgileniyoruz. Balımızın analizlerini düzenli yaptırıyoruz.', 'Saf, Doğal, Çam Balımız\r\n\r\nBalımızı da diğer tüm mahsüllerimiz gibi çiftliğimizde üretiyoruz. Başka bir yerden almayız. Ballarımızda çoluk çocuk ailece tüketebileceğiniz, o eski gerçek bal tadını bulabilirsiniz. Emin olabilirsiniz ki ballarımız da glikoz kesinlikle yoktur. Üretim aşamasında dışarıdan başka bir koruyucu veya katkı kesinlikle eklenmez. Çiçek ballarımızın petekleri yılın bir kısmında Konya Ilgın yöresinde, çam ballarımızın ise Aydın Doğanbey’de bulunur. Buna gezici arıcılık denir. Peteklerden yılda bir defa bal hasadı yapılır. Her şey bir yana balın kalitesini biz değil arılarımız belirler. Arıların çiçekten aldığı nükleer ve flora belirler. Bizim kaliteye herhangi bir etkimiz olamaz ve olmamalıdır. Biz sadece onların bal üretmeleriiçin en uygun ortamı yaratırız. Sonunda da ballarını süzüp size ulaştırmak kalır. \r\n\r\nBallarımız düzenli olarak ilgili kurumlarca kontrol edilir. Türk Akreditasyon Kurumu (TÜRKAK) akreditesine sahip laboratuvar tarafından analiz edilir. Buna göre; balımızın Hambal/Protein oranı Türk Gıda Kodeksi\'nde (TGK) belirtilmiş orandadır. Örneğin Prolin, balda baskın halde bulunan bir aminoasittir; arıların balı doğal ortamda üretip üretmediklerinin bir göstergesidir. Balımızda prolin miktarı 560 mg/kg’dır; TGK’ndeki değer ise 300 mg/kg’dır.\r\n\r\nÜrün İçeriği : 450 gr Çam Balı\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlerında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/VPQ0lr.png', 6, 30),
(40, 'Acı Biber Reçeli 240 Gr', '240 Gr Acı Biber Reçeli\r\n', 'Acı biber reçelimizi kırmızı kapya biber, atom acı biber, pancar şekeri ve biraz da limon suyu ile pişirdik. Farklı, özel bir tattır. Özellikle deniz ürünlerinin, etlerin yanında sos olarak kullanabilirsiniz.', 'Nefis Acı Biber Reçelimiz! \r\n\r\nKıpkırmızı acı biberlerimizle yaptığımız yeni bir lezzet: Acı Biber Reçeli.\r\nSeveni ve müdavimi çok olduğunu duyduk, biz de sizin için hazırladık. Acı biber reçelini kırmızı kapya biber, atom acı biber, şeker ve biraz da limon suyu ile pişirdik. Önce bir kaşıkla tadına bakın; tatlı bir lezzet gelecek damağınıza sonra acısını alacaksınız. Öyle bambaşka bir tat… İsterseniz kahvaltıda tüketebilir ya da yemeklerin yanında ikram edebilirsiniz. Peynir ekmek ikilisinin ve ızgaraların yanına çok yakışıyor. Kırmızı veya beyaz etle yapılan ızgaraların yanına tatlı-acı bir sos olarak çok güzel oluyor. \r\n\r\nSalataların üzerine gezdirebilir, kızartmaların yanında sos yapabilir; mücver gibi yemeklerin yanına lezzetlendirici gibi kullanabilirsiniz. Bu zıt lezzetlerin bir araya gelerek oluşturduğu harika lezzeti karides gibi farklı deniz ürünlerinin, tavuk yemeklerinin yanında da kullanabilirsiniz. Kızartılmış böreklerle, mücverlerle, hamurlu kızartmalarla, köftelerle, haburgerlerle bir arada ikram edebilirsiniz. Afiyet olsun. \r\n\r\nÜrün İçeriği : 240 gr cam kavanozunda acı biber reçeli\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlerında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/r603gN.png', 6, 31),
(41, 'Doğal Ev Yapımı Pekmez ( Armut ) 800 Gr', '800 Gr Armut Pekmezi\r\n', 'Armut pekmezlerimizi şekersiz olarak pişiriyoruz. Tamamen katkısız ve kendi üretimimizdir. Çiftliğimizin mevsiminde dalından meyveleriyle, ev yapımı olarak hazırlıyoruz.', 'Katkısız, Keni Üretimimiz Armut Pekmezi!\r\n\r\nPekmezlerimizde meyvelerimiz ve sudan başka hiçbir şey yok. Meyvesi de bahçelerimizden... Kendimiz topluyor, kendimiz pişiriyoruz. Ev yapımı olarak kavanozlara dolduruyoruz. Pekmezlerimizi şeker yerine çeşitli tariflerinde kullanan müdavimlerimiz de var. Hatta öğün niyetine yoğurdun üzerine ekliyor, kaşık kaşık yiyoruz. İnanın çok lezzetli oluyor. \r\n\r\nArmut pekmezimizi bahçelerimizin Tatlım armuduyla, sadece su ile kaynatarak pişiriyoruz. Daha sonra kaynattığımız pekmezi süzerek suyunu alıyoruz, Bu nedenle içerisinde meyvenin posası yoktur. Şekersiz olarak pişirilir. Tamamen katkısız ve kendi üretimimizdir. 12 yaşından bu yana pekmez, reçel ve marmelat yapan Metin Usta\'mızın mutfağında hazırlanıyor. Reçel ve pekmezlerimizi sadece mevsiminde kendi bahçelerimizde topladığımız meyvelerle pişiyoruz. Çiftliğimizin maharetlisi Metin Usta\'nın yıllardır uyguladığı usüllerle pişiyor. Bol meyveli reçelimizin sırrı çiftliğimizin havası, suyu; Metin Usta\'nın emekleri... \r\n\r\nKavanoz İçeriği: 800 gr ev yapımı, şekersiz armut pekmezi\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/guvenletuketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/ZM5ZLZ.png', 6, 19),
(45, 'Ev Yapımı Domates Reçeli 450 Gr', '450 Gr Domates Reçeli\r\n', 'Domates reçelimizi çiftiğimizi şeker domatesleriye yaparız çünkü kendi doğal tatlı lezzeti reçel yapımına çok uygundur. Ev yapımı ve katkısızdır.', 'Katkısız, Kendi Üretimimiz Domates Reçeli!\r\n\r\nEğer daha önce denediyeseniz bile bir de bizim domates reçelimizi deneyin. Çiftliğizim domates reçelini başka yerde bulamazsınız. Reçelimizi kendi yetiştirdiğimiz şeker domateslerimizle yapıyoruz.  İçerisinde %10 oranında şeker pancarı şekeri bulunuyor. Geri kalanı tamamen çiftliğimizin nefis, doğal şeker domatesleri ve biraz su. Geleneksel, katkısız ve ev yapımıdır. Domates reçelimizi de 12 yaşından bu yana pekmez, reçel ve marmelat yapan Metin Ustamızın mutfağında hazırlanıyor.\r\n\r\nDomates reçelimizin bir kere tadına baktığınızda kahvaltılarınızdan eksik etmek istemeyeceksiniz. \r\n\r\nKavanoz İçeriği: 450 gr katkısız ev yapımı domates reçeli\r\n\r\nBol meyveli, çok lezzetli!\r\n\r\nReçellerimizi sadece mevsiminde kendi bahçelerimizde topladığımız ürünlerle pişiyoruz. Çiftliğimizin maharetlisi Metin Usta\'nın yıllardır uyguladığı usüllerle pişiyor. Bol meyveli reçelimizin sırrı çiftliğimizin havası, suyu; Metin Usta\'nın emekleri...\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlarında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/LZvypG.png', 6, 21),
(46, 'Doğal Bal 450 Gr ( Çam Balı )', '450 Gr Çam Balı\r\n', 'Çiftliğimizde arılarımız mis kokulu çiçeklerden aldıkları özütleri bala çeviriyor. Ballarımızı da sadece çiftliğimizde üretiyoruz, bal peteklerimizle kendimiz ilgileniyoruz. Balımızın analizlerini düzenli yaptırıyoruz.', 'Saf, Doğal, Çam Balımız\r\n\r\nBalımızı da diğer tüm mahsüllerimiz gibi çiftliğimizde üretiyoruz. Başka bir yerden almayız. Ballarımızda çoluk çocuk ailece tüketebileceğiniz, o eski gerçek bal tadını bulabilirsiniz. Emin olabilirsiniz ki ballarımız da glikoz kesinlikle yoktur. Üretim aşamasında dışarıdan başka bir koruyucu veya katkı kesinlikle eklenmez. Çiçek ballarımızın petekleri yılın bir kısmında Konya Ilgın yöresinde, çam ballarımızın ise Aydın Doğanbey’de bulunur. Buna gezici arıcılık denir. Peteklerden yılda bir defa bal hasadı yapılır. Her şey bir yana balın kalitesini biz değil arılarımız belirler. Arıların çiçekten aldığı nükleer ve flora belirler. Bizim kaliteye herhangi bir etkimiz olamaz ve olmamalıdır. Biz sadece onların bal üretmeleriiçin en uygun ortamı yaratırız. Sonunda da ballarını süzüp size ulaştırmak kalır. \r\n\r\nBallarımız düzenli olarak ilgili kurumlarca kontrol edilir. Türk Akreditasyon Kurumu (TÜRKAK) akreditesine sahip laboratuvar tarafından analiz edilir. Buna göre; balımızın Hambal/Protein oranı Türk Gıda Kodeksi\'nde (TGK) belirtilmiş orandadır. Örneğin Prolin, balda baskın halde bulunan bir aminoasittir; arıların balı doğal ortamda üretip üretmediklerinin bir göstergesidir. Balımızda prolin miktarı 560 mg/kg’dır; TGK’ndeki değer ise 300 mg/kg’dır.\r\n\r\nÜrün İçeriği : 450 gr Çam Balı\r\n\r\nKimyasal yok, Mumlama yok!\r\n\r\nKendi çiftçilerimizle dedelerimizin yetiştirdiği gibi doğal ve sağlıklı tarım yapıyoruz. Dünyanın en iyi teknolojisini kullanıyoruz. ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin. )\r\n\r\nÜrünlerimiz tamamen doğal, hormonsuz ve GDO’suz!\r\n\r\nAmacımız kimyasal kullanmadan ve verimi gözetmeden önden tedbirimizi alarak ürün yetiştirmek. Hiç ilaç kullanmadan yada minimum seviyelerde ve iyi tarım standartlerında önlemler alarak ( Bu konuda daha fazla bilgi için lütfen Hasanbey.com/güvenletüketebilirsiniz sayfamızı ziyaret edin.) sizlere zamanında dalından toplanmış hiçbir kimyasal hormon barındırmayan ürünler sunuyoruz. Ürünlerimiz hormonla değil bombus arılarıyla tamamen doğal yöntemlerle dölleniyor. Seralarımızda kimyasal ilaç kullanmak yerine insan sağlığını tehdit etmeyen fiziksel önlemler alarak sağlıklı ve güvenli ürünler yetiştirmekteyiz.', 'http://i.hizliresim.com/VPQ0lr.png', 6, 23);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `unique_id` varchar(23) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `encrypted_password` varchar(80) NOT NULL,
  `salt` varchar(10) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `users`
--

INSERT INTO `users` (`id`, `unique_id`, `name`, `email`, `encrypted_password`, `salt`, `created_at`, `updated_at`) VALUES
(1, '5988f351de1f49.51630455', '1', '1', 'V08ppa91tXPwxhI7AlH+Fj8mbZRkMDg3MzlhYmE0', 'd08739aba4', '2017-08-07 23:10:09', NULL);

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `siparis`
--
ALTER TABLE `siparis`
  ADD PRIMARY KEY (`siparis_id`);

--
-- Tablo için indeksler `urunler`
--
ALTER TABLE `urunler`
  ADD PRIMARY KEY (`urun_id`);

--
-- Tablo için indeksler `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_id` (`unique_id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `siparis`
--
ALTER TABLE `siparis`
  MODIFY `siparis_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
--
-- Tablo için AUTO_INCREMENT değeri `urunler`
--
ALTER TABLE `urunler`
  MODIFY `urun_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=47;
--
-- Tablo için AUTO_INCREMENT değeri `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
